--- # Error handling example
- hosts: all
  user: ec2-user
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Execute a command that will fail
      command: /bin/false
      ignore_errors: yes
    - name: Install telnet
      yum: pkg=telnet state=latest
