--- # Outline to Playbook Translation
- hosts: all
  user: ec2-user
  become: yes
  gather_facts: no
  tasks:
    - name: date/time stamp when playbook starts
      command: /bin/date
      register: timestamp_start
    - debug: var=timestamp_start
    - name: install apache
      yum: pkg=httpd state=latest
      notify: start httpd
    - name: start apache
      service: name=httpd state=restarted
    - name: verify web service is running
      command: /sbin/service httpd status
      register: result
    - debug: var=result
    - name: install client software - telnet
      yum: pkg=telnet state=latest
    - name: install client software - lynx
      yum: pkg=lynx state=latest
    - name: log all installed packages
      command: yum list installed
      register: installed_result
    - debug: var=installed_result
    - name: date/time stamp when playbook stops
      command: /bin/date
      register: timestamp_start
    - debug: var=timestamp_stop
  handlers:
  - name: start httpd
    service: name=httpd state=restarted
