--- # Outline to Playbook Translation
- hosts: all
  user: ec2-user
  become: yes
  gather_facts: no
  tasks:
    - name: date/time stamp when playbook starts
      raw: /bin/date > playbook_start.log
    - name: install apache
      yum: pkg=httpd state=latest
    - name: start apache
      service: name=httpd state=restarted
    - name: verify web service is running
      command: /sbin/service httpd status
      register: result
    - debug: var=result
    - name: install client software - telnet
      yum: pkg=telnet state=latest
    - name: install client software - lynx
      yum: pkg=lynx state=latest
    - name: log all installed packages
      raw: yum list installed > installed.log
    - name: date/time stamp when playbook stops
      raw: /bin/date > playbook_stop.log
