--- #prompt for user package example
- hosts: all
  user: ec2-user
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_prompt:
    - name: pkgtoinstall
      prompt: Install which package?
      default: telnet
      private: no
  tasks:
    - name: Install the indicated package
      yum: pkg={{ pkgtoinstall }} state=latest
