--- # Tag functionality example
- hosts: all
  user: ec2-user
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install the telnet and lynx packages
      yum: pkg={{ item }} state=latest
      with_items:
        - telnet
        - lynx
      tags:
        - packages
    - name: Verify that telnet was installed
      raw: yum list installed | grep telnet > /tmp/pkgs.log
      tags:
        - verification
