---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    project_dir: ~/dev/terraform/ansible/
  vars_prompt:
    - name: terraform_state
      prompt: Desired Terraform state (planned, present, absent)
      private: no
      default: present
  tasks:
    - name: Run Terraform
      terraform:
        project_path: "{{ project_dir }}"
        state: "{{ terraform_state }}"
    - name: write hosts file
      shell: aws ec2 describe-instances --filters "Name=tag-key,Values=Ansible" | grep PublicIpAddress | awk -F ":" '{print $2}' | sed 's/[",]//g' > hosts
