---
- hosts: all
  user: ec2-user
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Installing Apache Web Server
      yum: pkg=httpd state=latest
    - name: Start Apache
      service: name=httpd state=restarted
    - name: Verify Service Status
      shell: /sbin/service httpd status
      register: result
      until: result.stdout.find("running") != -1
      retries: 5
      delay: 5
    - debug: var=result
